config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root 'blog/posts#index'

  # /authors/posts
  namespace :authors do
    get '/account/edit_profile' => 'accounts#edit', as: :edit_profile
    put '/info' => 'accounts#update_info', as: :info
    get '/account/change_password' => 'accounts#get_password', as: :edit_password
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'published' => 'posts#publish', on: :member
      put 'unpublished' => 'posts#unpublish', on: :member

    end
  end


  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def display_error_messages
    errors.full_messages.join('. ') << '.' if errors.any?
  end
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates :name, :presence => true, on: :update

  def chg_password(attributes)
    update(password: attributes[:new_password], password_confirmation: attributes[:new_password_confirmation])
  end

  def gravatar_image_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name
    else
      'Author'
    end
  end

  private

  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  body             :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  # acts_as_taggable_on :skills, :interests

  belongs_to :author
  has_many :comments

  scope :most_recent, -> { order(published_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.paginate(:page => page, per_page: 3) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }

  scope :list_for, -> (page, tag) do
      recent_paginated(page).with_tag(tag)
  end



  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Published #{published_at.strftime('%-b %-d,%Y')}"
    else
      'Not Published Yet'
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'author'

end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def edit

    end

    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully Updated'
      else
        flash[:warning] = current_author.display_error_messages
      end
      redirect_to authors_edit_profile_path
    end

    def get_password

    end

    def change_password
      if current_author.valid_password?(author_password_params[:current_password])
        if current_author.chg_password(author_password_params)
          sign_in(current_author, bypass: true)
          flash[:success] = 'Password Changed Successfully'
        else
          flash[:danger] = current_author.display_error_messages
        end

      else
        flash[:danger] = 'Incorrect Password' #current_author.errors.full_messages.join('. ') << '.'
      end
      redirect_to authors_edit_password_path

    end

    private
    def author_info_params
      params.require(:author).permit(:name, :email, :bio)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end

  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    def index
      @posts = current_author.posts.most_recent
    end


    def show
    end

    def new
      @post = current_author.posts.new
    end

    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :body, :banner_image_url, :tag_list)
    end
  end

end

app/controllers/blog/pages_controller.rb
module Blog

  class PagesController < BlogController
    def about
    end

    def contact
    end
  end

end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController


    def index
      # @posts = Post.paginate(:page => params[:page])
      @posts = storage.list_for(params[:page], params[:tag])
    end


    def show
      @post = storage.friendly.find(params[:id])
    end

    def storage
      Post.published
    end

  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/accounts/edit.html.erb
<% provide(:page_title, 'Update Profile') %>

<div class="row justify-content-center">
  <div class="col-md-6">
  <!--Basic Information Section-->
    <%= form_tag authors_info_path, method: :put do %>
        <%= fields_for :author do |f| %>
          <div class="card">
            <div class="card-body">
              <div class="card-title">
                Profile Information
              </div>
            </div>

            <ul class="list-group list-group-flush">

              <li class="list-group-item">
                <div class="field">
                  <%= image_tag(current_author.gravatar_image_url) %>
                </div>
              </li>
              <li class="list-group-item">
                <div class="field">
                  <%= f.label :name %>
                  <%= f.text_field :name, value: current_author.name, class: 'form-control' %>
                </div>
              </li>

              <li class="list-group-item">
                <div class="field">
                  <%= f.label :email %>
                  <%= f.text_field :email, value: current_author.email, class: 'form-control' %>
                </div>
              </li>
              <li class="list-group-item">
                <div class="field">
                  <%= f.label :bio %>
                  <%= f.text_area :bio, value: current_author.bio,  class: 'form-control' %>
                </div>
              </li>

              <li class="list-group-item">
                <div class="field">
                  <%= f.submit 'Update Profile',  class: 'btn btn-primary' %>
                </div>
              </li>

            </ul>
          </div>

        <% end %>

      <% end %>
    </div>

</div>

app/views/authors/accounts/get_password.html.erb
<% provide(:page_title, 'Change Password') %>

<div class="row justify-content-center">

  <!--Update Password Section-->
  <div class="col-md-6 ">
    <%= form_tag authors_change_password_path, method: :put do %>
        <%= fields_for :author do |f| %>

            <div class="card">

              <div class="card-body">
                <div class="card-title">
                  Change Password
                </div>
              </div>

              <ul class="list-group list-group-flush">

                <li class="list-group-item">
                  <div class="field">
                    <%= f.label :current_password %>
                    <%= f.password_field :current_password, class: 'form-control' %>
                  </div>
                </li>

                <li class="list-group-item">
                  <div class="field">
                    <%= f.label :new_password %>
                    <%= f.password_field :new_password,  class: 'form-control' %>
                  </div>
                </li>
                <li class="list-group-item">
                  <div class="field">
                    <%= f.label :new_password_confirmation %>
                    <%= f.password_field :new_password_confirmation,  class: 'form-control' %>
                  </div>
                </li>

                <li class="list-group-item">
                  <div class="field">
                    <%= f.submit 'Update Password',  class: 'btn btn-warning' %>
                  </div>
                </li>

              </ul>
            </div>

        <% end %>

    <% end %>

  </div>
</div>

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-4">

    <div class="card">
      <div class="card-body">
        <% if @post.new_record? %>
            <h4 class="card-title">New Post</h4>
        <% else %>
            <b> Edit</b>
            <span class="tiny-text"><%= @post.title %></span>
        <% end %>

      </div>
      <ul class="list-group list-group-flush">

        <li class="list-group-item">
          <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </li>

        <li class="list-group-item">
          <div class="field">
            <%= f.label :banner_image_url %>
            <%= f.text_field :banner_image_url,  class: 'form-control' %>
          </div>
        </li>
        <li class="list-group-item">
          <div class="field">
            <%= f.label :description %>
            <%= f.text_area :description,  class: 'form-control' %>
          </div>
        </li>

        <li class="list-group-item">
          <div class="field">
            <%= f.label 'Tags' %>
            <%= f.text_area :tag_list,  class: 'form-control' %>
          </div>
        </li>


      </ul>
    </div>

  </div>

  <div class="col-md-8">

    <div class="field">
      <%= f.text_area :body %>
    </div>

  </div>

</div>

<div class="text-center" style="margin-top: 20px" role="group">
  <%= f.submit 'Save Post', class: 'btn btn-secondary btn-success btn-md' %> |
  <% if @post.persisted? %>
      <%= link_to 'Show', @post, class: 'btn btn-secondary btn-primary btn-md' %>
      |
  <% end %>
      <%= link_to 'Back', authors_posts_path, class: 'btn btn-secondary btn-warning btn-md' %>

</div>







<% end %>

app/views/authors/posts/_post.html.erb
<tr>
  <td> <%= link_to post.title, authors_post_path(post) %> </td>
  <td></td>
  <% if post.published? %>
      <td> <%= link_to 'Unpublish', unpublished_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %> </td>
  <% else %>
      <td> <%= link_to 'Publish', published_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %> </td>
  <% end %>
  <td> <%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %> </td>
  <td> <%= link_to 'Remove', authors_post_path(post), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: 'Are you sure?'} %> </td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:authors, 'active') %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:authors, 'active') %>

<div class="row">
  <p>
    <%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>
  </p>
  <br>
  <table class="table table-striped">
    <tr>
      <th colspan="5">Title</th>
    </tr>
    <%= render @posts %>
  </table>

</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %> <!-- Display title on the tab -->
<% provide(:authors, 'New Post') %>


<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:authors, 'active') %>


<div class="row justify-content-center">
  <div class="col-md-10 col-lg-8 ">
    <h1 class="text-center"><%= @post.title %></h1>
    <p class="text-center"><%= @post.display_day_published %></p>
    <p class="text-center">
      <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
     | <%= link_to 'Delete', authors_post_path(@post), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: 'Are you sure?'} %>
    </p>
    <%= @post.body.html_safe %>
  </div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, 'active') %>
<h1>About Us</h1>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'active') %>
<h1>Contact Us</h1>

app/views/blog/posts/_post.html.erb
<div class="col-sm-6 col-lg-4">
    <div class="card mb-3 border-0">

      <%= link_to post do %>
          <img class="card-img-top img-fluid" src="<%= post.banner_image_url %>" alt="Post Image">
      <% end %>
      <div class="card-body">
        <h4 class="card-title"><%= link_to post.title, post %></h4>
        <p class="tags"><%= raw post.tags.map{ |t| link_to t.name, posts_path(tag: t.name) }.join(', ')  %></p>
        <p class="card-subtitle mb-2 text-muted"><%= post.display_day_published %></p>
        <%= link_to post do %>
            <p class="card-text lead"><%= truncate(post.description, length:130) %></p>
        <% end %>

      </div>
    </div>

</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>


  <div class="row">
    <%= render @posts %>
  </div>



<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @posts %>
  </div>
  <%= will_paginate @posts, container: false %>
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<div class="row justify-content-center">
  <div class="col-md-10 col-lg-8 ">
    <h1 class="text-center"><%= @post.title %></h1>
    <h6 class="text-center"><%= @post.display_day_published %></h6>
    <%= @post.body.html_safe %>

    <div class="author-bio text-center">
      <%= image_tag(@post.author.gravatar_image_url) %>
      <h4> <%= @post.author.name %> </h4>
      <h6 class="bio"> <%= @post.author.bio %> </h6>
    </div>

    <div id="disqus_thread"></div>
    <noscript>
      Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
    </noscript>
  </div>
</div>


<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

     var disqus_config = function () {
     this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
     this.page.identifier = '<%= @post.slug %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
     };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://everythingbosun.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">
      Bosun's<span class="light">blog</span>
    </a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#exCollapsingNavbar" aria-expanded="false" aria-controls="navCollapse" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="exCollapsingNavbar">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if author_signed_in? %>

          <li class="nav-item dropdown author-nav">
              <a class="nav-link dropdown-toggle <%= yield(:authors) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag(current_author.gravatar_image_url) %>
                <%= current_author.display_name %>
              </a>
              <div class="dropdown-menu border-0" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'My Posts', authors_posts_path, class: 'dropdown-item' %>
                <%= link_to 'Update Profile', authors_edit_profile_path, class: 'dropdown-item' %>
                <%= link_to 'Change Password', authors_edit_password_path, class: 'dropdown-item' %>
                <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: 'dropdown-item' %>

              </div>
            </li>

        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %> | Bosun's Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js"> </script>

</head>

<body>
<%= render 'layouts/navbar' %>

<div class="container <%= controller_name %> <%= action_name %>">
  <% if flash.any? %>
      <% flash.keys.each do |key| %>
          <div class="alert alert-dismissible alert-<%= key.to_s %>  fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[key] %>
          </div>

      <% end %>

  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Bosun's Blog</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400,700|Montserrat:400,400i,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>